import dotenv from 'dotenv';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { connectDB } from './config/db.js';
import User from './models/User.js';
import Company from './models/Company.js';
import Material from './models/Material.js';
import Transaction from './models/Transaction.js';

dotenv.config();

export const seedDatabase = async () => {
  try {
    const isConnected = await connectDB();
    if (!isConnected) {
      console.error('❌ Cannot seed database: MongoDB connection failed. Make sure MONGO_URI is set.');
      process.exit(1);
    }

    console.log('🧹 Clearing existing collections...');
    await Promise.all([
      User.deleteMany({}),
      Company.deleteMany({}),
      Material.deleteMany({}),
      Transaction.deleteMany({}),
    ]);

    console.log('🏢 Seeding Companies...');
    const companies = await Company.create([
      {
        name: 'ABC Packaging Pvt Ltd',
        description: 'Large-scale industrial corrugated cardboard and folding carton manufacturer with zero-landfill diversion goals.',
        industry: 'Industrial Packaging',
        businessType: 'Manufacturer',
        email: 'info@abcpackaging.com',
        phone: '+91 98250 11223',
        website: 'https://abcpackaging.example.com',
        location: {
          address: 'Plot 42, GIDC Industrial Estate',
          city: 'Ahmedabad',
          state: 'Gujarat',
          country: 'India',
          latitude: 23.0225,
          longitude: 72.5714,
        },
        verificationStatus: 'verified',
        circularityScore: 94,
        rating: 4.9,
        totalTransactions: 142,
        totalMaterialsExchanged: 380,
        totalWasteDiverted: 89000,
        totalCarbonAvoided: 83.6,
      },
      {
        name: 'GreenPack Industries',
        description: 'Eco-conscious consumer goods packaging and thermoformed biodegradable container producer.',
        industry: 'Sustainable Packaging',
        businessType: 'Converter',
        email: 'supply@greenpack.example.com',
        phone: '+91 98251 44556',
        website: 'https://greenpack.example.com',
        location: {
          address: 'Sector 18, Sanand Industrial Area',
          city: 'Sanand',
          state: 'Gujarat',
          country: 'India',
          latitude: 22.9868,
          longitude: 72.3815,
        },
        verificationStatus: 'trusted',
        circularityScore: 91,
        rating: 4.8,
        totalTransactions: 98,
        totalMaterialsExchanged: 240,
        totalWasteDiverted: 54000,
        totalCarbonAvoided: 52.1,
      },
      {
        name: 'EcoCycle Materials',
        description: 'Industrial polymer recycling, regrind processing, and closed-loop pelletizing facility.',
        industry: 'Plastic Recycling',
        businessType: 'Recycler',
        email: 'contact@ecocycle.example.com',
        phone: '+91 98252 77889',
        website: 'https://ecocycle.example.com',
        location: {
          address: 'Chakan MIDC Phase 2',
          city: 'Pune',
          state: 'Maharashtra',
          country: 'India',
          latitude: 18.7606,
          longitude: 73.8636,
        },
        verificationStatus: 'trusted',
        circularityScore: 96,
        rating: 4.95,
        totalTransactions: 210,
        totalMaterialsExchanged: 610,
        totalWasteDiverted: 142000,
        totalCarbonAvoided: 138.4,
      },
      {
        name: 'Urban Retail Solutions',
        description: 'Omnichannel fulfillment and logistics network handling high-volume protective dunnage and shipping crates.',
        industry: 'Retail & E-commerce',
        businessType: 'Retailer',
        email: 'procurement@urbanretail.example.com',
        phone: '+91 98253 99001',
        website: 'https://urbanretail.example.com',
        location: {
          address: 'Bhiwandi Logistics Park, Unit 7',
          city: 'Mumbai',
          state: 'Maharashtra',
          country: 'India',
          latitude: 19.2967,
          longitude: 73.0631,
        },
        verificationStatus: 'verified',
        circularityScore: 88,
        rating: 4.7,
        totalTransactions: 76,
        totalMaterialsExchanged: 195,
        totalWasteDiverted: 38000,
        totalCarbonAvoided: 35.7,
      },
      {
        name: 'CircularBox Manufacturing',
        description: 'Secondary crating, heavy-duty honeycomb boards, and specialized export packaging provider.',
        industry: 'Cardboard & Paper Products',
        businessType: 'Manufacturer',
        email: 'ops@circularbox.example.com',
        phone: '+91 98254 22334',
        website: 'https://circularbox.example.com',
        location: {
          address: 'Peenya Industrial Area, 3rd Stage',
          city: 'Bengaluru',
          state: 'Karnataka',
          country: 'India',
          latitude: 13.0285,
          longitude: 77.5197,
        },
        verificationStatus: 'verified',
        circularityScore: 89,
        rating: 4.75,
        totalTransactions: 84,
        totalMaterialsExchanged: 215,
        totalWasteDiverted: 46000,
        totalCarbonAvoided: 43.2,
      },
      {
        name: 'ReLoop Logistics',
        description: 'Green multimodal logistics fleet specialized in circular backhaul routing and certified reverse transport.',
        industry: 'Supply Chain & Transport',
        businessType: 'Logistics',
        email: 'dispatch@reloop.example.com',
        phone: '+91 98255 66778',
        website: 'https://reloop.example.com',
        location: {
          address: 'Manesar Freight Corridor, NH48',
          city: 'Gurugram',
          state: 'Haryana',
          country: 'India',
          latitude: 28.3547,
          longitude: 76.9405,
        },
        verificationStatus: 'trusted',
        circularityScore: 95,
        rating: 4.9,
        totalTransactions: 312,
        totalMaterialsExchanged: 820,
        totalWasteDiverted: 195000,
        totalCarbonAvoided: 184.2,
      },
    ]);

    const [abcCo, greenPackCo, ecoCycleCo, urbanRetailCo, circularBoxCo, reLoopCo] = companies;

    console.log('👤 Seeding Users...');
    const defaultPassword = 'Password123!';
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(defaultPassword, salt);

    const users = await User.create([
      {
        name: 'Rajesh Sharma',
        email: 'rajesh@abcpackaging.com',
        password: hashedPassword,
        phone: '+91 98250 11223',
        role: 'company_admin',
        company: abcCo._id,
        isVerified: true,
      },
      {
        name: 'Ananya Mehta',
        email: 'ananya@greenpack.example.com',
        password: hashedPassword,
        phone: '+91 98251 44556',
        role: 'company_admin',
        company: greenPackCo._id,
        isVerified: true,
      },
      {
        name: 'Vikram Patel',
        email: 'vikram@ecocycle.example.com',
        password: hashedPassword,
        phone: '+91 98252 77889',
        role: 'recycler',
        company: ecoCycleCo._id,
        isVerified: true,
      },
      {
        name: 'Priya Iyer',
        email: 'priya@urbanretail.example.com',
        password: hashedPassword,
        phone: '+91 98253 99001',
        role: 'buyer',
        company: urbanRetailCo._id,
        isVerified: true,
      },
      {
        name: 'Kunal Deshmukh',
        email: 'kunal@circularbox.example.com',
        password: hashedPassword,
        phone: '+91 98254 22334',
        role: 'supplier',
        company: circularBoxCo._id,
        isVerified: true,
      },
      {
        name: 'Amitabh Sen',
        email: 'amitabh@reloop.example.com',
        password: hashedPassword,
        phone: '+91 98255 66778',
        role: 'logistics',
        company: reLoopCo._id,
        isVerified: true,
      },
      {
        name: 'Platform Administrator',
        email: 'admin@circula.exchange',
        password: hashedPassword,
        phone: '+91 98000 00000',
        role: 'admin',
        company: abcCo._id,
        isVerified: true,
      },
    ]);

    const [uAbc, uGreenPack, uEcoCycle, uUrban, uCircularBox] = users;

    console.log('📦 Seeding Materials (16 realistic circular listings)...');
    const materials = await Material.create([
      {
        supplier: uAbc._id,
        company: abcCo._id,
        name: 'Corrugated Cardboard Bales (Double-Wall Overrun)',
        category: 'cardboard',
        description: 'Clean, unprinted surplus double-wall slotted container offcuts from pharmaceutical packaging runs. Bundled in high-density 500kg wire bales.',
        quantity: 2500,
        unit: 'kg',
        price: 8.5,
        currency: 'INR',
        condition: 'good',
        grade: 'Virgin Kraft Flute B/C',
        dimensions: '120 x 80 x 100 cm bales',
        weight: 500,
        recyclability: 100,
        transactionType: 'sell',
        location: abcCo.location,
        tags: ['double-wall', 'kraft', 'baled', 'unprinted'],
        images: ['https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 2.0,
        estimatedWasteDiverted: 2500,
        estimatedVirginMaterialAvoided: 2125,
      },
      {
        supplier: uAbc._id,
        company: abcCo._id,
        name: 'Die-Cut Cardboard Sheet Offcuts',
        category: 'cardboard',
        description: 'Flat single-wall corrugated board cutoffs, ideal for inner partitions, divider pads, and edge protectors.',
        quantity: 1200,
        unit: 'kg',
        price: 7.2,
        currency: 'INR',
        condition: 'new',
        grade: 'Grade A Testliner',
        dimensions: '80 x 60 cm sheets',
        weight: 1200,
        recyclability: 100,
        transactionType: 'sell',
        location: abcCo.location,
        tags: ['single-wall', 'dividers', 'flat-sheets'],
        images: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 0.96,
        estimatedWasteDiverted: 1200,
        estimatedVirginMaterialAvoided: 1020,
      },
      {
        supplier: uGreenPack._id,
        company: greenPackCo._id,
        name: 'HDPE Regrind Flakes (Translucent Blow Mold)',
        category: 'plastic',
        description: 'Washed and granulate-sorted high-density polyethylene flakes with melt flow index 0.35 g/10min. Clean bottle grade surplus.',
        quantity: 1800,
        unit: 'kg',
        price: 42.0,
        currency: 'INR',
        condition: 'recyclable',
        grade: 'MFI 0.35 Blow Molding Grade',
        dimensions: 'Gaylord boxes (500kg each)',
        weight: 1800,
        recyclability: 98,
        transactionType: 'sell',
        location: greenPackCo.location,
        tags: ['HDPE', 'regrind', 'translucent', 'pelletizing'],
        images: ['https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 2.52,
        estimatedWasteDiverted: 1800,
        estimatedVirginMaterialAvoided: 1530,
      },
      {
        supplier: uGreenPack._id,
        company: greenPackCo._id,
        name: 'Post-Industrial LDPE Stretch Film Rolls',
        category: 'plastic',
        description: 'Surplus rolls of 23-micron linear low-density cast stretch wrap. Clean, virgin-grade film from test setups.',
        quantity: 950,
        unit: 'kg',
        price: 36.0,
        currency: 'INR',
        condition: 'new',
        grade: 'LLDPE Grade 1',
        dimensions: '500mm width, 300m roll',
        weight: 950,
        recyclability: 100,
        transactionType: 'sell',
        location: greenPackCo.location,
        tags: ['LDPE', 'stretch-film', 'pallet-wrap'],
        images: ['https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 1.33,
        estimatedWasteDiverted: 950,
        estimatedVirginMaterialAvoided: 807,
      },
      {
        supplier: uUrban._id,
        company: urbanRetailCo._id,
        name: 'Heat-Treated Euro Pine Pallets (EPAL Standard)',
        category: 'pallet',
        description: 'ISPM-15 certified 4-way entry heavy-duty wooden shipping pallets. Inspected and repaired, ready for immediate warehouse storage.',
        quantity: 350,
        unit: 'units',
        price: 280.0,
        currency: 'INR',
        condition: 'good',
        grade: 'EPAL 1 / ISPM-15',
        dimensions: '1200 x 800 x 144 mm',
        weight: 22,
        recyclability: 100,
        transactionType: 'sell',
        location: urbanRetailCo.location,
        tags: ['EPAL', 'heat-treated', 'wooden-pallets', 'ISPM-15'],
        images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 4.77,
        estimatedWasteDiverted: 7700,
        estimatedVirginMaterialAvoided: 6545,
      },
      {
        supplier: uUrban._id,
        company: urbanRetailCo._id,
        name: 'Industrial Four-Way Wooden Pallets (1200x1000mm)',
        category: 'pallet',
        description: 'Sturdy perimeter base standard shipping pallets suitable for rack storage and high-cube sea containers.',
        quantity: 200,
        unit: 'units',
        price: 240.0,
        currency: 'INR',
        condition: 'used',
        grade: 'Grade B Heavy-Duty',
        dimensions: '1200 x 1000 x 150 mm',
        weight: 25,
        recyclability: 100,
        transactionType: 'sell',
        location: urbanRetailCo.location,
        tags: ['pallets', 'wooden', 'heavy-duty'],
        images: ['https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 3.1,
        estimatedWasteDiverted: 5000,
        estimatedVirginMaterialAvoided: 4250,
      },
      {
        supplier: uEcoCycle._id,
        company: ecoCycleCo._id,
        name: 'PP Strapping Band Granulate (Black Recycled)',
        category: 'plastic',
        description: 'Reprocessed polypropylene pellets derived from shredded logistics strapping. High tensile strength, suitable for injection molding.',
        quantity: 3200,
        unit: 'kg',
        price: 34.0,
        currency: 'INR',
        condition: 'recyclable',
        grade: 'Injection Grade PP',
        dimensions: '25kg poly bags',
        weight: 3200,
        recyclability: 100,
        transactionType: 'sell',
        location: ecoCycleCo.location,
        tags: ['PP', 'granulate', 'injection-molding', 'black-pellets'],
        images: ['https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 4.48,
        estimatedWasteDiverted: 3200,
        estimatedVirginMaterialAvoided: 2720,
      },
      {
        supplier: uEcoCycle._id,
        company: ecoCycleCo._id,
        name: 'Clear PET Flakes (Hot-Washed Fiber Grade)',
        category: 'plastic',
        description: 'Flakes derived from sorted post-industrial thermoformed blister packaging. Moisture content < 1.0%, PVC contamination < 50 ppm.',
        quantity: 4500,
        unit: 'kg',
        price: 48.0,
        currency: 'INR',
        condition: 'recyclable',
        grade: 'Hot-Washed PET Flake',
        dimensions: '1000kg Big Bags',
        weight: 4500,
        recyclability: 100,
        transactionType: 'sell',
        location: ecoCycleCo.location,
        tags: ['PET', 'clear-flakes', 'fiber-grade'],
        images: ['https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 6.3,
        estimatedWasteDiverted: 4500,
        estimatedVirginMaterialAvoided: 3825,
      },
      {
        supplier: uCircularBox._id,
        company: circularBoxCo._id,
        name: 'Heavy-Duty Kraft Paper Roll Offcuts (80-120 GSM)',
        category: 'paper',
        description: 'Unbleached natural brown kraft paper reels from slitting line setups. Ideal for void fill, wrapping, and interleaving.',
        quantity: 1600,
        unit: 'kg',
        price: 11.5,
        currency: 'INR',
        condition: 'new',
        grade: '100 GSM Virgin Kraft',
        dimensions: 'Core diameter 76mm, reels 600mm width',
        weight: 1600,
        recyclability: 100,
        transactionType: 'sell',
        location: circularBoxCo.location,
        tags: ['kraft-paper', 'reels', 'void-fill', 'wrapping'],
        images: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 1.2,
        estimatedWasteDiverted: 1600,
        estimatedVirginMaterialAvoided: 1360,
      },
      {
        supplier: uCircularBox._id,
        company: circularBoxCo._id,
        name: 'Molded Pulp Cushioning Trays (Shock Absorption)',
        category: 'paper',
        description: '100% biodegradable molded fiber corner protectors and device trays. Never exposed to moisture.',
        quantity: 800,
        unit: 'kg',
        price: 14.0,
        currency: 'INR',
        condition: 'good',
        grade: 'Thermoformed Fiber',
        dimensions: 'Standard nestable corner protectors',
        weight: 800,
        recyclability: 100,
        transactionType: 'free_claim',
        location: circularBoxCo.location,
        tags: ['molded-pulp', 'free-claim', 'biodegradable', 'cushioning'],
        images: ['https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 0.6,
        estimatedWasteDiverted: 800,
        estimatedVirginMaterialAvoided: 680,
      },
      {
        supplier: uUrban._id,
        company: urbanRetailCo._id,
        name: 'Collapsible Attached-Lid Plastic Totes (ALC 60L)',
        category: 'plastic',
        description: 'Standard retail distribution nestable distribution containers with textured security bottoms and inter-locking lids.',
        quantity: 180,
        unit: 'units',
        price: 380.0,
        currency: 'INR',
        condition: 'good',
        grade: 'Virgin Polypropylene (Impact Modified)',
        dimensions: '600 x 400 x 365 mm',
        weight: 3.2,
        recyclability: 100,
        transactionType: 'sell',
        location: urbanRetailCo.location,
        tags: ['reusable-packaging', 'totes', 'ALC', 'closed-loop'],
        images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 0.8,
        estimatedWasteDiverted: 576,
        estimatedVirginMaterialAvoided: 490,
      },
      {
        supplier: uAbc._id,
        company: abcCo._id,
        name: 'Molded Fiber Glass Bottle Dividers (12-Pack)',
        category: 'paper',
        description: 'Recycled newsprint pulp bottle partitions. Designed to safely transport 750ml glass bottles with zero breakage.',
        quantity: 2200,
        unit: 'units',
        price: 4.5,
        currency: 'INR',
        condition: 'new',
        grade: 'Recycled Fiber Grade',
        dimensions: '330 x 240 x 290 mm',
        weight: 0.25,
        recyclability: 100,
        transactionType: 'exchange',
        location: abcCo.location,
        tags: ['partitions', 'bottle-packaging', 'exchange', 'protective'],
        images: ['https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 0.41,
        estimatedWasteDiverted: 550,
        estimatedVirginMaterialAvoided: 467,
      },
      {
        supplier: uEcoCycle._id,
        company: ecoCycleCo._id,
        name: 'Industrial Amber Glass Packaging Cullet',
        category: 'glass',
        description: 'Color-sorted crushed amber glass containers, magnetic metal extracted and washed. Furnace ready for bottle manufacture.',
        quantity: 5000,
        unit: 'kg',
        price: 3.8,
        currency: 'INR',
        condition: 'recyclable',
        grade: 'Furnace Cullet Grade 1',
        dimensions: 'Bulk Tipper Load',
        weight: 5000,
        recyclability: 100,
        transactionType: 'sell',
        location: ecoCycleCo.location,
        tags: ['cullet', 'amber-glass', 'furnace-ready'],
        images: ['https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 1.49,
        estimatedWasteDiverted: 5000,
        estimatedVirginMaterialAvoided: 4250,
      },
      {
        supplier: uGreenPack._id,
        company: greenPackCo._id,
        name: 'Reconditioned Steel Drum Enclosures (210L Tight-Head)',
        category: 'metal',
        description: 'UN-certified decontaminated, internally lined 55-gallon drums with bungs. Leak tested to 200 kPa.',
        quantity: 60,
        unit: 'units',
        price: 850.0,
        currency: 'INR',
        condition: 'good',
        grade: 'UN 1A1 Heavy Gauge Steel',
        dimensions: 'Height 880mm, Diameter 585mm',
        weight: 18,
        recyclability: 100,
        transactionType: 'sell',
        location: greenPackCo.location,
        tags: ['steel-drums', 'reconditioned', 'UN-rated'],
        images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 7.53,
        estimatedWasteDiverted: 1080,
        estimatedVirginMaterialAvoided: 918,
      },
      {
        supplier: uAbc._id,
        company: abcCo._id,
        name: 'Honeycomb Paperboard Cushioning Panels (25mm)',
        category: 'cardboard',
        description: 'Engineered structural paper honeycomb panels for heavy machinery crating and export pallet tops.',
        quantity: 650,
        unit: 'kg',
        price: 18.0,
        currency: 'INR',
        condition: 'new',
        grade: 'Cell Size 10mm, 25mm thickness',
        dimensions: '2400 x 1200 x 25 mm',
        weight: 650,
        recyclability: 100,
        transactionType: 'sell',
        location: abcCo.location,
        tags: ['honeycomb', 'crating', 'export-packaging'],
        images: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 0.52,
        estimatedWasteDiverted: 650,
        estimatedVirginMaterialAvoided: 552,
      },
      {
        supplier: uCircularBox._id,
        company: circularBoxCo._id,
        name: 'Corrugated Flute Offcuts & Trim Waste (Baled)',
        category: 'cardboard',
        description: 'Dry stored clean trimmings from slotting machines. Ready for direct repulping.',
        quantity: 3500,
        unit: 'kg',
        price: 6.8,
        currency: 'INR',
        condition: 'recyclable',
        grade: 'OCC Grade 11',
        dimensions: 'Wire-tied 400kg bales',
        weight: 3500,
        recyclability: 100,
        transactionType: 'sell',
        location: circularBoxCo.location,
        tags: ['OCC', 'bales', 'repulping', 'mill-ready'],
        images: ['https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80'],
        status: 'active',
        estimatedCarbonAvoided: 2.8,
        estimatedWasteDiverted: 3500,
        estimatedVirginMaterialAvoided: 2975,
      },
    ]);

    console.log('🤝 Seeding Transactions (5 realistic exchanges with order numbers)...');
    await Transaction.create([
      {
        orderNumber: 'CM-2048',
        buyer: uGreenPack._id,
        buyerCompany: greenPackCo._id,
        seller: uAbc._id,
        sellerCompany: abcCo._id,
        material: materials[0]._id, // 2500kg Cardboard
        quantity: 2000,
        materialCost: 17000,
        transportCost: 1200,
        totalCost: 18200,
        currency: 'INR',
        status: 'delivered',
        pickupLocation: abcCo.location,
        destinationLocation: greenPackCo.location,
        distance: 32,
        estimatedTransportCarbon: 6.08,
        estimatedTotalCarbonAvoided: 1.59,
        deliveryDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        orderNumber: 'CM-2049',
        buyer: uUrban._id,
        buyerCompany: urbanRetailCo._id,
        seller: uGreenPack._id,
        sellerCompany: greenPackCo._id,
        material: materials[3]._id, // LDPE stretch film
        quantity: 800,
        materialCost: 28800,
        transportCost: 3500,
        totalCost: 32300,
        currency: 'INR',
        status: 'in_transit',
        pickupLocation: greenPackCo.location,
        destinationLocation: urbanRetailCo.location,
        distance: 120,
        estimatedTransportCarbon: 9.12,
        estimatedTotalCarbonAvoided: 1.11,
      },
      {
        orderNumber: 'CM-2050',
        buyer: uCircularBox._id,
        buyerCompany: circularBoxCo._id,
        seller: uUrban._id,
        sellerCompany: urbanRetailCo._id,
        material: materials[4]._id, // Euro Pallets
        quantity: 150,
        materialCost: 42000,
        transportCost: 4200,
        totalCost: 46200,
        currency: 'INR',
        status: 'pickup_scheduled',
        pickupLocation: urbanRetailCo.location,
        destinationLocation: circularBoxCo.location,
        distance: 85,
        estimatedTransportCarbon: 26.6,
        estimatedTotalCarbonAvoided: 2.02,
      },
      {
        orderNumber: 'CM-2051',
        buyer: uEcoCycle._id,
        buyerCompany: ecoCycleCo._id,
        seller: uGreenPack._id,
        sellerCompany: greenPackCo._id,
        material: materials[2]._id, // HDPE Regrind Flakes
        quantity: 1500,
        materialCost: 63000,
        transportCost: 2800,
        totalCost: 65800,
        currency: 'INR',
        status: 'confirmed',
        pickupLocation: greenPackCo.location,
        destinationLocation: ecoCycleCo.location,
        distance: 140,
        estimatedTransportCarbon: 19.95,
        estimatedTotalCarbonAvoided: 2.08,
      },
      {
        orderNumber: 'CM-2052',
        buyer: uAbc._id,
        buyerCompany: abcCo._id,
        seller: uCircularBox._id,
        sellerCompany: circularBoxCo._id,
        material: materials[8]._id, // Kraft Paper Roll Offcuts
        quantity: 1000,
        materialCost: 11500,
        transportCost: 1800,
        totalCost: 13300,
        currency: 'INR',
        status: 'pending',
        pickupLocation: circularBoxCo.location,
        destinationLocation: abcCo.location,
        distance: 48,
        estimatedTransportCarbon: 4.56,
        estimatedTotalCarbonAvoided: 0.74,
      },
    ]);

    console.log('✅ Seed completed successfully!');
    console.log('-------------------------------------------');
    console.log(`Created: ${companies.length} companies`);
    console.log(`Created: ${users.length} users (Default password: ${defaultPassword})`);
    console.log(`Created: ${materials.length} circular materials`);
    console.log(`Created: 5 transactions (CM-2048 to CM-2052)`);
    console.log('-------------------------------------------');

    if (process.argv[1].endsWith('seed.js')) {
      await mongoose.disconnect();
      process.exit(0);
    }
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

// Execute if run directly
if (process.argv[1].endsWith('seed.js')) {
  seedDatabase();
}
